# build environment
FROM node:latest as builder
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ADD package.json /app/package.json
RUN npm install --silent
ADD . /app
RUN npm run build

# production environment
FROM zzrot/alpine-caddy
COPY --from=builder /app/build /var/www/html
EXPOSE 80